baseURL: /
enableRobotsTXT: true
enableEmoji: true
# Provide .LastMod values
enableGitInfo: true

languages:
  en:
    title: Kured
    description: Kured (KUbernetes REboot Daemon) is a Kubernetes daemonset that performs safe automatic node reboots when the need to do so is indicated by the package management system of the underlying OS.
    languageCode: en-gb

module:
  proxy: direct
  hugoVersion:
    extended: true
    min: 0.73.0
  imports:
    - path: github.com/google/docsy
    - path: github.com/google/docsy/dependencies
  mounts:
    - source: content/en
      target: content

outputs:
  home: [HTML]
  page: [HTML]

params:
  copyright: The Kured authors
  github_repo: https://github.com/kubereboot/website
  github_branch: main
  github_project_repo: https://github.com/kubereboot/kured
  ui:
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact: true
    sidebar_menu_foldable: true
    sidebar_menu_truncate: 1000
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable: false
    # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable: true
    # Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
    # -> change once we have SVG
    navbar_logo: false
    # Set to true to disable the About link in the site footer
    footer_about_disable: false
    readingtime:
      enable: false
  links:
    user:
      - name: Slack
        url: 'https://cloud-native.slack.com/archives/kured'
        icon: fa-brands fa-slack
        desc: Chat with other project developers
      - name: Twitter
        url: 'https://twitter.com/kubereboot'
        icon: fa-brands fa-twitter
        desc: Follow us on Twitter to get the latest news!
    developer:
      - name: GitHub
        url: 'https://github.com/kubereboot'
        icon: fa-brands fa-github
        desc: Development takes place here!
      - name: YouTube
        url: 'https://www.youtube.com/playlist?list=PL7wDX91NpJl_rKYrAtd8zr2XszpexS1eE'
        icon: fa-brands fa-youtube
        desc: View the Kured Dev meeting recordings
      - name: Mailing list
        url: 'https://lists.cncf.io/g/cncf-kured-dev'
        icon: fa-solid fa-envelope
        desc: Sign up to the Kured mailing list

menus:
  main:
  - url: https://github.com/kubereboot/kured
    name: Github
    pre: "<i class='fab fa-github'></i> "
    weight: 100
